services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: posadmin
      POSTGRES_PASSWORD: pos123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: mSq123!!
      TrustServerCertificate: true
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-container
    restart: always
    environment:
      ORACLE_PASSWORD: ora123
      APP_USER: system
      APP_USER_PASSWORD: ora123
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

  spring-app:
    build: .
    container_name: spring-app-container
    restart: always
    depends_on:
      - postgres
      - mssql
      - oracle
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      SPRING_DATASOURCE_POSTGRES_URL: jdbc:postgresql://postgres-container:5432/userdb
      SPRING_DATASOURCE_POSTGRES_USERNAME: posadmin
      SPRING_DATASOURCE_POSTGRES_PASSWORD: pos123
      SPRING_DATASOURCE_MSSQL_URL: jdbc:sqlserver://mssql-container:1433;databaseName=productdb;encrypt=true;TrustServerCertificate=true
      SPRING_DATASOURCE_MSSQL_USERNAME: sa
      SPRING_DATASOURCE_MSSQL_PASSWORD: mSq123!!
      SPRING_DATASOURCE_ORACLE_URL: jdbc:oracle:thin:@oracle-container:1521/FREEPDB1
      SPRING_DATASOURCE_ORACLE_USERNAME: system
      SPRING_DATASOURCE_ORACLE_PASSWORD: ora123

volumes:
  postgres_data:
  mssql_data:
  oracle_data:
